<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="9" passed="7" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-15T22:26:57 ICT" name="Default suite" finished-at="2023-05-15T22:27:07 ICT" duration-ms="10428">
    <groups>
    </groups>
    <test started-at="2023-05-15T22:26:57 ICT" name="Default test" finished-at="2023-05-15T22:27:07 ICT" duration-ms="10428">
      <class name="UiTest.NhanVienTest">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:UiTest.NhanVienTest@72057ecf]" started-at="2023-05-15T22:26:57 ICT" name="beforeClass" finished-at="2023-05-15T22:26:59 ICT" duration-ms="2166" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="testTrongThongTin()[pri:1, instance:UiTest.NhanVienTest@72057ecf]" started-at="2023-05-15T22:26:59 ICT" name="testTrongThongTin" finished-at="2023-05-15T22:27:00 ICT" duration-ms="1475" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTrongThongTin -->
        <test-method signature="testTenSai()[pri:2, instance:UiTest.NhanVienTest@72057ecf]" started-at="2023-05-15T22:27:00 ICT" name="testTenSai" finished-at="2023-05-15T22:27:01 ICT" duration-ms="891" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTenSai -->
        <test-method signature="testTrungMaNV()[pri:3, instance:UiTest.NhanVienTest@72057ecf]" started-at="2023-05-15T22:27:01 ICT" name="testTrungMaNV" finished-at="2023-05-15T22:27:02 ICT" duration-ms="990" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTrungMaNV -->
        <test-method signature="testXoaNVTrongMaNV()[pri:4, instance:UiTest.NhanVienTest@72057ecf]" started-at="2023-05-15T22:27:02 ICT" name="testXoaNVTrongMaNV" finished-at="2023-05-15T22:27:04 ICT" duration-ms="2089" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Mã nhân viên trống!] but found [Mã nhân viên đã tồn tại! thao tác thêm thất bại!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Mã nhân viên trống!] but found [Mã nhân viên đã tồn tại! thao tác thêm thất bại!]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at UiTest.NhanVienTest.testXoaNVTrongMaNV(NhanVienTest.java:105)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testXoaNVTrongMaNV -->
        <test-method signature="testSuaNVSaiMaNV()[pri:5, instance:UiTest.NhanVienTest@72057ecf]" started-at="2023-05-15T22:27:04 ICT" name="testSuaNVSaiMaNV" finished-at="2023-05-15T22:27:05 ICT" duration-ms="632" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuaNVSaiMaNV -->
        <test-method signature="testXoaThanhCong()[pri:6, instance:UiTest.NhanVienTest@72057ecf]" started-at="2023-05-15T22:27:05 ICT" name="testXoaThanhCong" finished-at="2023-05-15T22:27:06 ICT" duration-ms="534" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Xóa thành công!] but found [Cập nhật thất bại!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Xóa thành công!] but found [Cập nhật thất bại!]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at UiTest.NhanVienTest.testXoaThanhCong(NhanVienTest.java:173)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testXoaThanhCong -->
        <test-method signature="testThemNVTrungMa()[pri:7, instance:UiTest.NhanVienTest@72057ecf]" started-at="2023-05-15T22:27:06 ICT" name="testThemNVTrungMa" finished-at="2023-05-15T22:27:06 ICT" duration-ms="603" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThemNVTrungMa -->
        <test-method signature="testMatKhauKhongTrung()[pri:8, instance:UiTest.NhanVienTest@72057ecf]" started-at="2023-05-15T22:27:06 ICT" name="testMatKhauKhongTrung" finished-at="2023-05-15T22:27:07 ICT" duration-ms="528" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMatKhauKhongTrung -->
        <test-method signature="testThemThanhCong()[pri:9, instance:UiTest.NhanVienTest@72057ecf]" started-at="2023-05-15T22:27:07 ICT" name="testThemThanhCong" finished-at="2023-05-15T22:27:07 ICT" duration-ms="476" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThemThanhCong -->
      </class> <!-- UiTest.NhanVienTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
